"""
gen_decoder_3nrm_v3.py
Generates decoder_3nrm.v v3.0 - 3NRM-RRNS decoder with FSM-based sequential MRC.

v3.0 TIMING FIX (Bug #70):
  Root cause: Dynamic modulo operations (e.g., a2_prod % mrc_mj where mrc_mj is a
  register variable) synthesize to full divider circuits with ~45-51 logic levels
  (~18-21ns), exceeding the 20ns clock period at 50MHz.

  Fix: Replace all dynamic modulo with case-based constant modulo functions.
  Each case branch uses a compile-time constant modulus, allowing Vivado to
  optimize to ~5-8 LUT levels (~2-3ns per operation).

  The modulus index (idx_i, idx_j, idx_k) is saved as a register in MRC_S1,
  and used by the case-based functions in subsequent stages.

Architecture: Single MRC engine + FSM iterates through all 84 triplets sequentially.
- LUT usage: ~1500-3000 LUT (vs ~64,700 LUT for 84-parallel version)
- Latency: ~842 clock cycles (well within 10,000-cycle watchdog)
- Timing: All paths < 20ns at 50MHz (case-based constant modulo ~3ns each)
"""

from math import gcd

def extended_gcd(a, b):
    if a == 0: return b, 0, 1
    g, x, y = extended_gcd(b % a, a)
    return g, y - (b // a) * x, x

def mod_inv(a, m):
    a = a % m
    _, x, _ = extended_gcd(a, m)
    return x % m

MODS = [64, 63, 65, 31, 29, 23, 19, 17, 11]

# Generate all 84 triplets
triplets = [(i,j,k) for i in range(9) for j in range(i+1,9) for k in range(j+1,9)]
assert len(triplets) == 84

def get_mrc_constants(i, j, k):
    mi, mj, mk = MODS[i], MODS[j], MODS[k]
    inv_ij  = mod_inv(mi, mj)
    inv_ijk = mod_inv((mi * mj) % mk, mk)
    return inv_ij, inv_ijk, mi, mj, mk

# Generate Verilog
lines = []
def L(s=""): lines.append(s)

L("// =============================================================================")
L("// File: decoder_3nrm.v")
L("// Description: 3NRM-RRNS Decoder - FSM Sequential MRC Architecture")
L("//              Algorithm: Residue Number System with Moduli Set:")
L("//              Non-redundant: {64, 63, 65}")
L("//              Redundant:     {31, 29, 23, 19, 17, 11}")
L("//              Part of FPGA Multi-Algorithm Fault-Tolerant Test System")
L("// Version: v3.0 (Timing Fix: Case-based constant modulo replaces dynamic modulo)")
L("//")
L("// TIMING FIX (v3.0 vs v2.0):")
L("//   Root cause: Dynamic modulo (e.g., prod % mrc_mj where mrc_mj is a register)")
L("//   synthesizes to a full divider circuit with ~45-51 logic levels (~18-21ns),")
L("//   exceeding the 20ns clock period at 50MHz. WNS = -14.235ns.")
L("//")
L("//   Fix: All modulo operations use case-based constant modulo functions.")
L("//   Each case branch has a compile-time constant modulus, allowing Vivado to")
L("//   optimize to ~5-8 LUT levels (~2-3ns). Expected WNS > 0 at 50MHz.")
L("//")
L("// ARCHITECTURE: Single MRC engine + FSM iterates through all 84 triplets.")
L("//   - LUT: ~1500-3000 (case-based modulo is more LUT-efficient than dynamic)")
L("//   - Latency: ~842 clock cycles (well within 10,000-cycle watchdog)")
L("//")
L("// INPUT BIT LAYOUT (48 bits valid, right-aligned in 64-bit bus):")
L("//   [63:48] = padding (ignored)")
L("//   [47:42] = r0 = received residue mod 64  (6 bits)")
L("//   [41:36] = r1 = received residue mod 63  (6 bits)")
L("//   [35:29] = r2 = received residue mod 65  (7 bits)")
L("//   [28:24] = r3 = received residue mod 31  (5 bits)")
L("//   [23:19] = r4 = received residue mod 29  (5 bits)")
L("//   [18:14] = r5 = received residue mod 23  (5 bits)")
L("//   [13:9]  = r6 = received residue mod 19  (5 bits)")
L("//   [8:4]   = r7 = received residue mod 17  (5 bits)")
L("//   [3:0]   = r8 = received residue mod 11  (4 bits)")
L("// =============================================================================")
L()
L("`timescale 1ns / 1ps")
L()
L("module decoder_3nrm (")
L("    input  wire        clk,")
L("    input  wire        rst_n,")
L("    input  wire        start,")
L("    input  wire [63:0] residues_in,")
L("    output reg  [15:0] data_out,")
L("    output reg         valid,")
L("    output reg         uncorrectable")
L(");")
L()
L("    // =========================================================================")
L("    // 1. FSM State Encoding")
L("    // =========================================================================")
L("    localparam ST_IDLE    = 4'd0;")
L("    localparam ST_LOAD    = 4'd1;")
L("    localparam ST_MRC_S1  = 4'd2;")
L("    localparam ST_MRC_S2  = 4'd3;")
L("    localparam ST_MRC_S3  = 4'd4;")
L("    localparam ST_MRC_S4  = 4'd5;")
L("    localparam ST_MRC_S5  = 4'd6;")
L("    localparam ST_DIST_S1 = 4'd7;")
L("    localparam ST_DIST_S2 = 4'd8;")
L("    localparam ST_DIST_S3 = 4'd9;")
L("    localparam ST_UPDATE  = 4'd10;")
L("    localparam ST_NEXT    = 4'd11;")
L("    localparam ST_DONE    = 4'd12;")
L()
L("    localparam NRM_MAX_ERRORS = 3;")
L()
L("    reg [3:0] state;")
L("    reg [6:0] trip_idx;  // 0..83: current triplet index")
L()
L("    // =========================================================================")
L("    // 2. Lookup Tables for 84 Triplets (synthesized as ROM/LUTRAM)")
L("    // =========================================================================")
L("    reg [6:0] lut_mi [0:83];")
L("    reg [6:0] lut_mj [0:83];")
L("    reg [6:0] lut_mk [0:83];")
L("    reg [6:0] lut_inv_ij  [0:83];")
L("    reg [6:0] lut_inv_ijk [0:83];")
L("    reg [3:0] lut_idx_i [0:83];")
L("    reg [3:0] lut_idx_j [0:83];")
L("    reg [3:0] lut_idx_k [0:83];")
L()
L("    initial begin")
for idx, (i, j, k) in enumerate(triplets):
    inv_ij, inv_ijk, mi, mj, mk = get_mrc_constants(i, j, k)
    L(f"        lut_mi[{idx:2d}]=7'd{mi}; lut_mj[{idx:2d}]=7'd{mj}; lut_mk[{idx:2d}]=7'd{mk};")
    L(f"        lut_inv_ij[{idx:2d}]=7'd{inv_ij}; lut_inv_ijk[{idx:2d}]=7'd{inv_ijk};")
    L(f"        lut_idx_i[{idx:2d}]=4'd{i}; lut_idx_j[{idx:2d}]=4'd{j}; lut_idx_k[{idx:2d}]=4'd{k};")
L("    end")
L()
L("    // =========================================================================")
L("    // 3. Received Residues Register Bank")
L("    // =========================================================================")
L("    reg [6:0] recv_r [0:8];")
L()
L("    // =========================================================================")
L("    // 4. MRC Computation Registers")
L("    // =========================================================================")
L("    reg [6:0] mrc_ri, mrc_rj, mrc_rk;")
L("    reg [6:0] mrc_mi, mrc_mj, mrc_mk;")
L("    reg [6:0] mrc_inv_ij, mrc_inv_ijk;")
L("    reg [3:0] mrc_idx_j, mrc_idx_k;  // v3.0: save modulus indices for case-based modulo")
L("    reg [6:0] mrc_a1;")
L("    reg [7:0] mrc_diff2;")
L("    reg [7:0] mrc_diff3;")
L("    reg [6:0] mrc_a2;")
L("    reg [7:0] mrc_a3raw;")
L("    reg [6:0] mrc_a3;")
L("    reg [17:0] mrc_x;")
L()
L("    // =========================================================================")
L("    // 5. Distance Computation Registers")
L("    // =========================================================================")
L("    reg [6:0] cand_r [0:8];")
L("    reg [3:0] cur_dist;")
L()
L("    // =========================================================================")
L("    // 6. MLD Accumulator")
L("    // =========================================================================")
L("    reg [3:0]  min_dist;")
L("    reg [15:0] best_x;")
L()
L("    // =========================================================================")
L("    // 7. Case-Based Constant Modulo Functions (v3.0 TIMING FIX)")
L("    // =========================================================================")
L("    // These functions replace dynamic modulo (prod % mrc_mj) with case statements")
L("    // where each branch uses a compile-time constant modulus.")
L("    // Vivado optimizes constant modulo to ~5-8 LUT levels (~2-3ns) vs")
L("    // dynamic modulo which requires ~45-51 LUT levels (~18-21ns).")
L("    //")
L("    // mod_by_idx_7bit: compute val % MODS[idx] for 7-bit result (max mod=65)")
L("    // Input: val up to 14-bit (product of two 7-bit values)")
L("    // Output: 7-bit result")
L("    function automatic [6:0] mod_by_idx_7bit(input [13:0] val, input [3:0] idx);")
L("        case (idx)")
L("            4'd0: mod_by_idx_7bit = val % 7'd64;")
L("            4'd1: mod_by_idx_7bit = val % 7'd63;")
L("            4'd2: mod_by_idx_7bit = val % 7'd65;")
L("            4'd3: mod_by_idx_7bit = val % 7'd31;")
L("            4'd4: mod_by_idx_7bit = val % 7'd29;")
L("            4'd5: mod_by_idx_7bit = val % 7'd23;")
L("            4'd6: mod_by_idx_7bit = val % 7'd19;")
L("            4'd7: mod_by_idx_7bit = val % 7'd17;")
L("            4'd8: mod_by_idx_7bit = val % 7'd11;")
L("            default: mod_by_idx_7bit = 7'd0;")
L("        endcase")
L("    endfunction")
L()
L("    // mod_by_idx_16bit: compute val % MODS[idx] for 16-bit input (candidate X)")
L("    // Input: val up to 16-bit (candidate X value)")
L("    // Output: 7-bit result")
L("    function automatic [6:0] mod_by_idx_16bit(input [15:0] val, input [3:0] idx);")
L("        case (idx)")
L("            4'd0: mod_by_idx_16bit = val % 7'd64;")
L("            4'd1: mod_by_idx_16bit = val % 7'd63;")
L("            4'd2: mod_by_idx_16bit = val % 7'd65;")
L("            4'd3: mod_by_idx_16bit = val % 7'd31;")
L("            4'd4: mod_by_idx_16bit = val % 7'd29;")
L("            4'd5: mod_by_idx_16bit = val % 7'd23;")
L("            4'd6: mod_by_idx_16bit = val % 7'd19;")
L("            4'd7: mod_by_idx_16bit = val % 7'd17;")
L("            4'd8: mod_by_idx_16bit = val % 7'd11;")
L("            default: mod_by_idx_16bit = 7'd0;")
L("        endcase")
L("    endfunction")
L()
L("    // =========================================================================")
L("    // 8. Combinational MRC Intermediate Signals (v3.0: case-based modulo)")
L("    // =========================================================================")
L("    // MRC_S2: a2 = (diff2 * inv_ij) % mj")
L("    // v3.0: use mod_by_idx_7bit with mrc_idx_j instead of % mrc_mj")
L("    wire [13:0] s2_prod  = mrc_diff2 * mrc_inv_ij;")
L("    wire [6:0]  s2_a2    = mod_by_idx_7bit(s2_prod, mrc_idx_j);")
L()
L("    // MRC_S3: a3_raw = (diff3 - (a2*mi % mk) + mk) % mk")
L("    // v3.0: use mod_by_idx_7bit with mrc_idx_k instead of % mrc_mk")
L("    wire [13:0] s3_a2mi_prod = mrc_a2 * mrc_mi;")
L("    wire [6:0]  s3_a2mi_mod  = mod_by_idx_7bit(s3_a2mi_prod, mrc_idx_k);")
L("    wire [7:0]  s3_a3raw = (mrc_diff3 >= s3_a2mi_mod) ?")
L("                           (mrc_diff3 - s3_a2mi_mod) :")
L("                           (mrc_diff3 + mrc_mk - s3_a2mi_mod);")
L()
L("    // MRC_S4: a3 = (a3_raw * inv_ijk) % mk")
L("    // v3.0: use mod_by_idx_7bit with mrc_idx_k instead of % mrc_mk")
L("    wire [13:0] s4_prod = mrc_a3raw * mrc_inv_ijk;")
L("    wire [6:0]  s4_a3   = mod_by_idx_7bit(s4_prod, mrc_idx_k);")
L()
L("    // MRC_S5: X = a1 + a2*mi + a3*mi*mj")
L("    wire [17:0] s5_x = {11'b0, mrc_a1} + ({11'b0, mrc_a2} * {11'b0, mrc_mi}) +")
L("                       ({11'b0, mrc_a3} * {11'b0, mrc_mi} * {11'b0, mrc_mj});")
L()
L("    // =========================================================================")
L("    // 9. Combinational Distance Computation (v3.0: case-based modulo)")
L("    // =========================================================================")
L("    // DIST_S1: compute cand_r[0..2] = X % {64, 63, 65}")
L("    wire [6:0] ds1_r0 = mrc_x[15:0] % 7'd64;")
L("    wire [6:0] ds1_r1 = mrc_x[15:0] % 7'd63;")
L("    wire [6:0] ds1_r2 = mrc_x[15:0] % 7'd65;")
L()
L("    // DIST_S2: compute cand_r[3..5] = X % {31, 29, 23}")
L("    wire [6:0] ds2_r3 = mrc_x[15:0] % 7'd31;")
L("    wire [6:0] ds2_r4 = mrc_x[15:0] % 7'd29;")
L("    wire [6:0] ds2_r5 = mrc_x[15:0] % 7'd23;")
L()
L("    // DIST_S3: compute cand_r[6..8] = X % {19, 17, 11}")
L("    wire [6:0] ds3_r6 = mrc_x[15:0] % 7'd19;")
L("    wire [6:0] ds3_r7 = mrc_x[15:0] % 7'd17;")
L("    wire [6:0] ds3_r8 = mrc_x[15:0] % 7'd11;")
L()
L("    // Hamming distance")
L("    wire [3:0] dist_comb =")
L("        ((cand_r[0] != recv_r[0]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[1] != recv_r[1]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[2] != recv_r[2]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[3] != recv_r[3]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[4] != recv_r[4]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[5] != recv_r[5]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[6] != recv_r[6]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[7] != recv_r[7]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[8] != recv_r[8]) ? 4'd1 : 4'd0);")
L()
L("    // =========================================================================")
L("    // 10. FSM")
L("    // =========================================================================")
L("    integer ii;")
L()
L("    always @(posedge clk or negedge rst_n) begin")
L("        if (!rst_n) begin")
L("            state         <= ST_IDLE;")
L("            trip_idx      <= 7'd0;")
L("            min_dist      <= 4'd9;")
L("            best_x        <= 16'd0;")
L("            cur_dist      <= 4'd9;")
L("            mrc_ri        <= 7'd0;")
L("            mrc_rj        <= 7'd0;")
L("            mrc_rk        <= 7'd0;")
L("            mrc_mi        <= 7'd1;")
L("            mrc_mj        <= 7'd1;")
L("            mrc_mk        <= 7'd1;")
L("            mrc_inv_ij    <= 7'd1;")
L("            mrc_inv_ijk   <= 7'd1;")
L("            mrc_idx_j     <= 4'd0;")
L("            mrc_idx_k     <= 4'd0;")
L("            mrc_a1        <= 7'd0;")
L("            mrc_diff2     <= 8'd0;")
L("            mrc_diff3     <= 8'd0;")
L("            mrc_a2        <= 7'd0;")
L("            mrc_a3raw     <= 8'd0;")
L("            mrc_a3        <= 7'd0;")
L("            mrc_x         <= 18'd0;")
L("            for (ii=0; ii<9; ii=ii+1) begin")
L("                recv_r[ii] <= 7'd0;")
L("                cand_r[ii] <= 7'd0;")
L("            end")
L("            data_out      <= 16'd0;")
L("            valid         <= 1'b0;")
L("            uncorrectable <= 1'b0;")
L("        end else begin")
L("            valid         <= 1'b0;")
L("            uncorrectable <= 1'b0;")
L()
L("            case (state)")
L()
L("                ST_IDLE: begin")
L("                    if (start) state <= ST_LOAD;")
L("                end")
L()
L("                ST_LOAD: begin")
L("                    recv_r[0] <= {1'b0, residues_in[47:42]};")
L("                    recv_r[1] <= {1'b0, residues_in[41:36]};")
L("                    recv_r[2] <=        residues_in[35:29];")
L("                    recv_r[3] <= {2'b0, residues_in[28:24]};")
L("                    recv_r[4] <= {2'b0, residues_in[23:19]};")
L("                    recv_r[5] <= {2'b0, residues_in[18:14]};")
L("                    recv_r[6] <= {2'b0, residues_in[13:9]};")
L("                    recv_r[7] <= {2'b0, residues_in[8:4]};")
L("                    recv_r[8] <= {3'b0, residues_in[3:0]};")
L("                    trip_idx  <= 7'd0;")
L("                    min_dist  <= 4'd9;")
L("                    best_x    <= 16'd0;")
L("                    state     <= ST_MRC_S1;")
L("                end")
L()
L("                ST_MRC_S1: begin")
L("                    // Load triplet parameters + save modulus indices for case-based modulo")
L("                    mrc_mi      <= lut_mi[trip_idx];")
L("                    mrc_mj      <= lut_mj[trip_idx];")
L("                    mrc_mk      <= lut_mk[trip_idx];")
L("                    mrc_inv_ij  <= lut_inv_ij[trip_idx];")
L("                    mrc_inv_ijk <= lut_inv_ijk[trip_idx];")
L("                    mrc_idx_j   <= lut_idx_j[trip_idx];  // v3.0: save for case-based modulo")
L("                    mrc_idx_k   <= lut_idx_k[trip_idx];  // v3.0: save for case-based modulo")
L("                    mrc_ri      <= recv_r[lut_idx_i[trip_idx]];")
L("                    mrc_rj      <= recv_r[lut_idx_j[trip_idx]];")
L("                    mrc_rk      <= recv_r[lut_idx_k[trip_idx]];")
L("                    state <= ST_MRC_S2;")
L("                end")
L()
L("                ST_MRC_S2: begin")
L("                    mrc_a1    <= mrc_ri;")
L("                    mrc_diff2 <= (mrc_rj >= mrc_ri) ? (mrc_rj - mrc_ri) :")
L("                                 (mrc_rj + mrc_mj - mrc_ri);")
L("                    mrc_diff3 <= (mrc_rk >= mrc_ri) ? (mrc_rk - mrc_ri) :")
L("                                 (mrc_rk + mrc_mk - mrc_ri);")
L("                    state <= ST_MRC_S3;")
L("                end")
L()
L("                ST_MRC_S3: begin")
L("                    // v3.0: s2_a2 uses mod_by_idx_7bit(s2_prod, mrc_idx_j)")
L("                    // mrc_idx_j is a registered value -> case branch is selected at runtime")
L("                    // but each branch has a CONSTANT modulus -> ~5-8 LUT levels")
L("                    mrc_a2 <= s2_a2;")
L("                    state  <= ST_MRC_S4;")
L("                end")
L()
L("                ST_MRC_S4: begin")
L("                    // v3.0: s3_a3raw uses mod_by_idx_7bit(s3_a2mi_prod, mrc_idx_k)")
L("                    mrc_a3raw <= s3_a3raw;")
L("                    state     <= ST_MRC_S5;")
L("                end")
L()
L("                ST_MRC_S5: begin")
L("                    // v3.0: s4_a3 uses mod_by_idx_7bit(s4_prod, mrc_idx_k)")
L("                    mrc_a3 <= s4_a3;")
L("                    state  <= ST_DIST_S1;")
L("                end")
L()
L("                ST_DIST_S1: begin")
L("                    mrc_x <= s5_x;")
L("                    state <= ST_DIST_S2;")
L("                end")
L()
L("                ST_DIST_S2: begin")
L("                    if (mrc_x <= 18'd65535) begin")
L("                        cand_r[0] <= ds1_r0;")
L("                        cand_r[1] <= ds1_r1;")
L("                        cand_r[2] <= ds1_r2;")
L("                    end else begin")
L("                        cand_r[0] <= 7'd127;")
L("                        cand_r[1] <= 7'd127;")
L("                        cand_r[2] <= 7'd127;")
L("                    end")
L("                    state <= ST_DIST_S3;")
L("                end")
L()
L("                ST_DIST_S3: begin")
L("                    if (mrc_x <= 18'd65535) begin")
L("                        cand_r[3] <= ds2_r3;")
L("                        cand_r[4] <= ds2_r4;")
L("                        cand_r[5] <= ds2_r5;")
L("                        cand_r[6] <= ds3_r6;")
L("                        cand_r[7] <= ds3_r7;")
L("                        cand_r[8] <= ds3_r8;")
L("                    end else begin")
L("                        cand_r[3] <= 7'd127; cand_r[4] <= 7'd127; cand_r[5] <= 7'd127;")
L("                        cand_r[6] <= 7'd127; cand_r[7] <= 7'd127; cand_r[8] <= 7'd127;")
L("                    end")
L("                    state <= ST_UPDATE;")
L("                end")
L()
L("                ST_UPDATE: begin")
L("                    cur_dist <= dist_comb;")
L("                    if (dist_comb < min_dist) begin")
L("                        min_dist <= dist_comb;")
L("                        best_x   <= mrc_x[15:0];")
L("                    end")
L("                    state <= ST_NEXT;")
L("                end")
L()
L("                ST_NEXT: begin")
L("                    if (trip_idx == 7'd83) begin")
L("                        state <= ST_DONE;")
L("                    end else begin")
L("                        trip_idx <= trip_idx + 1'b1;")
L("                        state    <= ST_MRC_S1;")
L("                    end")
L("                end")
L()
L("                ST_DONE: begin")
L("                    valid <= 1'b1;")
L("                    if (min_dist <= NRM_MAX_ERRORS) begin")
L("                        data_out      <= best_x;")
L("                        uncorrectable <= 1'b0;")
L("                    end else begin")
L("                        data_out      <= 16'd0;")
L("                        uncorrectable <= 1'b1;")
L("                    end")
L("                    state <= ST_IDLE;")
L("                end")
L()
L("                default: state <= ST_IDLE;")
L("            endcase")
L("        end")
L("    end")
L()
L("endmodule")

# Write to file
output_path = r"d:\FPGAproject\FPGA-RRNS-Project-V2\src\algo_wrapper\decoder_3nrm.v"
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {output_path}")
print(f"Total lines: {len(lines)}")
print(f"Triplets: {len(triplets)}")
print(f"v3.0 changes: dynamic modulo replaced with case-based constant modulo")
print(f"Expected timing improvement: ~21ns -> ~3ns per modulo operation")
