"""
gen_crrns.py
Generates encoder_crrns.v and decoder_crrns.v for C-RRNS (Traditional RRNS) algorithm.

C-RRNS Parameters:
  Non-redundant moduli (k=3): {64, 63, 65}
  Redundant moduli (n-k=6):   {67, 71, 73, 79, 83, 89}
  Total moduli (n=9):         {64, 63, 65, 67, 71, 73, 79, 83, 89}
  Codeword: 61 bits (6+6+7+7+7+7+7+7+7), right-aligned in 64-bit bus
  Error correction: t=3 (up to 3 erroneous residues)

Codeword bit layout (right-aligned in 64-bit bus):
  [63:61] = padding (3 bits, 0)
  [60:55] = r0 = x % 64  (6 bits)
  [54:49] = r1 = x % 63  (6 bits)
  [48:42] = r2 = x % 65  (7 bits)
  [41:35] = r3 = x % 67  (7 bits)
  [34:28] = r4 = x % 71  (7 bits)
  [27:21] = r5 = x % 73  (7 bits)
  [20:14] = r6 = x % 79  (7 bits)
  [13:7]  = r7 = x % 83  (7 bits)
  [6:0]   = r8 = x % 89  (7 bits)

Decoder: FSM sequential MLD (same architecture as decoder_3nrm.v v3.0)
  - 84 triplets C(9,3), 10 cycles per triplet
  - Total latency: 842 clock cycles
  - Case-based constant modulo (timing-safe at 50MHz)
"""

from math import gcd

def extended_gcd(a, b):
    if a == 0: return b, 0, 1
    g, x, y = extended_gcd(b % a, a)
    return g, y - (b // a) * x, x

def mod_inv(a, m):
    a = a % m
    _, x, _ = extended_gcd(a, m)
    return x % m

MODS = [64, 63, 65, 67, 71, 73, 79, 83, 89]
MOD_BITS = [6, 6, 7, 7, 7, 7, 7, 7, 7]

# Bit positions in 64-bit bus (MSB first, right-aligned)
# [60:55]=r0, [54:49]=r1, [48:42]=r2, [41:35]=r3, [34:28]=r4,
# [27:21]=r5, [20:14]=r6, [13:7]=r7, [6:0]=r8
BIT_HI = [60, 54, 48, 41, 34, 27, 20, 13, 6]
BIT_LO = [55, 49, 42, 35, 28, 21, 14,  7, 0]

# Generate all 84 triplets
triplets = [(i,j,k) for i in range(9) for j in range(i+1,9) for k in range(j+1,9)]
assert len(triplets) == 84

def get_mrc_constants(i, j, k):
    mi, mj, mk = MODS[i], MODS[j], MODS[k]
    inv_ij  = mod_inv(mi, mj)
    inv_ijk = mod_inv((mi * mj) % mk, mk)
    return inv_ij, inv_ijk, mi, mj, mk

# ============================================================
# Generate encoder_crrns.v
# ============================================================
enc_lines = []
def EL(s=""): enc_lines.append(s)

EL("// =============================================================================")
EL("// File: encoder_crrns.v")
EL("// Description: C-RRNS (Traditional RRNS) Encoder")
EL("//              Algorithm: Residue Number System with Moduli Set:")
EL("//              Non-redundant: {64, 63, 65}")
EL("//              Redundant:     {67, 71, 73, 79, 83, 89}")
EL("//              Part of FPGA Multi-Algorithm Fault-Tolerant Test System")
EL("// Version: v1.0")
EL("//")
EL("// CODEWORD FORMAT (61 bits valid, right-aligned in 64-bit bus):")
EL("//   [63:61] = 3'b0  (padding)")
EL("//   [60:55] = r0 = data_in % 64  (6 bits)")
EL("//   [54:49] = r1 = data_in % 63  (6 bits)")
EL("//   [48:42] = r2 = data_in % 65  (7 bits)")
EL("//   [41:35] = r3 = data_in % 67  (7 bits)")
EL("//   [34:28] = r4 = data_in % 71  (7 bits)")
EL("//   [27:21] = r5 = data_in % 73  (7 bits)")
EL("//   [20:14] = r6 = data_in % 79  (7 bits)")
EL("//   [13:7]  = r7 = data_in % 83  (7 bits)")
EL("//   [6:0]   = r8 = data_in % 89  (7 bits)")
EL("//   Total valid bits: 6+6+7+7+7+7+7+7+7 = 61 bits")
EL("//")
EL("// PIPELINE: 4 stages, 4-cycle latency")
EL("//   Stage E0: Input register")
EL("//   Stage E1: r0(% 64), r1(% 63), r2(% 65)")
EL("//   Stage E2: r3(% 67), r4(% 71), r5(% 73)")
EL("//   Stage E3: r6(% 79), r7(% 83), r8(% 89), pack and output")
EL("//")
EL("// INTERFACE: Identical to encoder_3nrm.v for drop-in compatibility.")
EL("// =============================================================================")
EL()
EL("`timescale 1ns / 1ps")
EL()
EL("module encoder_crrns (")
EL("    input  wire        clk,")
EL("    input  wire        rst_n,")
EL("    input  wire        start,")
EL("    input  wire [15:0] data_in_A,")
EL("    input  wire [15:0] data_in_B,   // Retained for interface compatibility; unused")
EL("    output reg  [63:0] residues_out_A,")
EL("    output reg  [63:0] residues_out_B,  // Always 64'd0 (single-channel mode)")
EL("    output reg         done")
EL(");")
EL()
EL("    // =========================================================================")
EL("    // Stage E0: Input Register")
EL("    // =========================================================================")
EL("    (* dont_touch = \"true\", max_fanout = 8 *) reg [15:0] data_e0;")
EL("    (* dont_touch = \"true\" *) reg start_e0;")
EL()
EL("    always @(posedge clk or negedge rst_n) begin")
EL("        if (!rst_n) begin data_e0 <= 16'd0; start_e0 <= 1'b0; end")
EL("        else begin data_e0 <= data_in_A; start_e0 <= start; end")
EL("    end")
EL()
EL("    // =========================================================================")
EL("    // Stage E1: r0(% 64), r1(% 63), r2(% 65)")
EL("    // % 64 = direct bit-select [5:0]")
EL("    // % 63: 64 ≡ 1 (mod 63), x = 64*x_hi + x_lo => x%63 = (x_hi+x_lo)%63")
EL("    // % 65: 64 ≡ -1 (mod 65), x%65 = (x_lo - x_hi + 65*16)%65")
EL("    // =========================================================================")
EL("    wire [5:0]  r0_e1_comb = data_e0[5:0];")
EL("    wire [10:0] r1_step1   = {1'b0, data_e0[15:6]} + {5'b0, data_e0[5:0]};")
EL("    wire [5:0]  r1_e1_comb = r1_step1 % 6'd63;")
EL("    wire [10:0] r2_step1   = {5'b0, data_e0[5:0]} + 11'd1040 - {1'b0, data_e0[15:6]};")
EL("    wire [6:0]  r2_e1_comb = r2_step1 % 7'd65;")
EL()
EL("    (* dont_touch = \"true\" *) reg [5:0]  r0_e1;")
EL("    (* dont_touch = \"true\" *) reg [5:0]  r1_e1;")
EL("    (* dont_touch = \"true\" *) reg [6:0]  r2_e1;")
EL("    (* dont_touch = \"true\", max_fanout = 8 *) reg [15:0] data_e1;")
EL("    (* dont_touch = \"true\" *) reg start_e1;")
EL()
EL("    always @(posedge clk or negedge rst_n) begin")
EL("        if (!rst_n) begin r0_e1<=6'd0; r1_e1<=6'd0; r2_e1<=7'd0; data_e1<=16'd0; start_e1<=1'b0; end")
EL("        else begin r0_e1<=r0_e1_comb; r1_e1<=r1_e1_comb; r2_e1<=r2_e1_comb; data_e1<=data_e0; start_e1<=start_e0; end")
EL("    end")
EL()
EL("    // =========================================================================")
EL("    // Stage E2: r3(% 67), r4(% 71), r5(% 73)")
EL("    // All direct % on 16-bit input (synthesizable, ~8 LUT levels)")
EL("    // =========================================================================")
EL("    wire [6:0] r3_e2_comb = data_e1 % 7'd67;")
EL("    wire [6:0] r4_e2_comb = data_e1 % 7'd71;")
EL("    wire [6:0] r5_e2_comb = data_e1 % 7'd73;")
EL()
EL("    (* dont_touch = \"true\" *) reg [5:0]  r0_e2;")
EL("    (* dont_touch = \"true\" *) reg [5:0]  r1_e2;")
EL("    (* dont_touch = \"true\" *) reg [6:0]  r2_e2;")
EL("    (* dont_touch = \"true\" *) reg [6:0]  r3_e2;")
EL("    (* dont_touch = \"true\" *) reg [6:0]  r4_e2;")
EL("    (* dont_touch = \"true\" *) reg [6:0]  r5_e2;")
EL("    (* dont_touch = \"true\", max_fanout = 8 *) reg [15:0] data_e2;")
EL("    (* dont_touch = \"true\" *) reg start_e2;")
EL()
EL("    always @(posedge clk or negedge rst_n) begin")
EL("        if (!rst_n) begin")
EL("            r0_e2<=6'd0; r1_e2<=6'd0; r2_e2<=7'd0;")
EL("            r3_e2<=7'd0; r4_e2<=7'd0; r5_e2<=7'd0;")
EL("            data_e2<=16'd0; start_e2<=1'b0;")
EL("        end else begin")
EL("            r0_e2<=r0_e1; r1_e2<=r1_e1; r2_e2<=r2_e1;")
EL("            r3_e2<=r3_e2_comb; r4_e2<=r4_e2_comb; r5_e2<=r5_e2_comb;")
EL("            data_e2<=data_e1; start_e2<=start_e1;")
EL("        end")
EL("    end")
EL()
EL("    // =========================================================================")
EL("    // Stage E3: r6(% 79), r7(% 83), r8(% 89), pack and output")
EL("    // =========================================================================")
EL("    wire [6:0] r6_e3_comb = data_e2 % 7'd79;")
EL("    wire [6:0] r7_e3_comb = data_e2 % 7'd83;")
EL("    wire [6:0] r8_e3_comb = data_e2 % 7'd89;")
EL()
EL("    // Pack 61-bit codeword (right-aligned in 64-bit bus)")
EL("    wire [63:0] packed_a = {")
EL("        3'd0,           // [63:61] padding")
EL("        r0_e2,          // [60:55] r0 = % 64 (6 bits)")
EL("        r1_e2,          // [54:49] r1 = % 63 (6 bits)")
EL("        r2_e2,          // [48:42] r2 = % 65 (7 bits)")
EL("        r3_e2,          // [41:35] r3 = % 67 (7 bits)")
EL("        r4_e2,          // [34:28] r4 = % 71 (7 bits)")
EL("        r5_e2,          // [27:21] r5 = % 73 (7 bits)")
EL("        r6_e3_comb,     // [20:14] r6 = % 79 (7 bits)")
EL("        r7_e3_comb,     // [13:7]  r7 = % 83 (7 bits)")
EL("        r8_e3_comb      // [6:0]   r8 = % 89 (7 bits)")
EL("    };")
EL()
EL("    always @(posedge clk or negedge rst_n) begin")
EL("        if (!rst_n) begin residues_out_A <= 64'd0; residues_out_B <= 64'd0; done <= 1'b0; end")
EL("        else begin")
EL("            done <= 1'b0;")
EL("            if (start_e2) begin")
EL("                residues_out_A <= packed_a;")
EL("                residues_out_B <= 64'd0;")
EL("                done           <= 1'b1;")
EL("            end")
EL("        end")
EL("    end")
EL()
EL("endmodule")

# Write encoder
enc_path = r"d:\FPGAproject\FPGA-RRNS-Project-V2\src\algo_wrapper\encoder_crrns.v"
with open(enc_path, "w", encoding="utf-8") as f:
    f.write("\n".join(enc_lines) + "\n")
print(f"Generated {enc_path} ({len(enc_lines)} lines)")

# ============================================================
# Generate decoder_crrns.v (FSM MLD, same architecture as decoder_3nrm v3.0)
# ============================================================
dec_lines = []
def DL(s=""): dec_lines.append(s)

DL("// =============================================================================")
DL("// File: decoder_crrns.v")
DL("// Description: C-RRNS (Traditional RRNS) Decoder - FSM Sequential MLD")
DL("//              Algorithm: Residue Number System with Moduli Set:")
DL("//              Non-redundant: {64, 63, 65}")
DL("//              Redundant:     {67, 71, 73, 79, 83, 89}")
DL("//              Part of FPGA Multi-Algorithm Fault-Tolerant Test System")
DL("// Version: v1.0")
DL("//")
DL("// ARCHITECTURE: FSM Sequential MLD (identical to decoder_3nrm.v v3.0)")
DL("//   - Single MRC engine + FSM iterates through all 84 triplets C(9,3)")
DL("//   - Case-based constant modulo (timing-safe at 50MHz)")
DL("//   - Latency: 842 clock cycles")
DL("//   - Error correction: t=3 (100% for random 3-error patterns)")
DL("//")
DL("// INPUT BIT LAYOUT (61 bits valid, right-aligned in 64-bit bus):")
DL("//   [63:61] = padding (ignored)")
DL("//   [60:55] = r0 = received residue mod 64  (6 bits)")
DL("//   [54:49] = r1 = received residue mod 63  (6 bits)")
DL("//   [48:42] = r2 = received residue mod 65  (7 bits)")
DL("//   [41:35] = r3 = received residue mod 67  (7 bits)")
DL("//   [34:28] = r4 = received residue mod 71  (7 bits)")
DL("//   [27:21] = r5 = received residue mod 73  (7 bits)")
DL("//   [20:14] = r6 = received residue mod 79  (7 bits)")
DL("//   [13:7]  = r7 = received residue mod 83  (7 bits)")
DL("//   [6:0]   = r8 = received residue mod 89  (7 bits)")
DL("// =============================================================================")
DL()
DL("`timescale 1ns / 1ps")
DL()
DL("module decoder_crrns_mld (")
DL("    input  wire        clk,")
DL("    input  wire        rst_n,")
DL("    input  wire        start,")
DL("    input  wire [63:0] residues_in,")
DL("    output reg  [15:0] data_out,")
DL("    output reg         valid,")
DL("    output reg         uncorrectable")
DL(");")
DL()
DL("    // =========================================================================")
DL("    // 1. FSM State Encoding")
DL("    // =========================================================================")
DL("    localparam ST_IDLE    = 4'd0;")
DL("    localparam ST_LOAD    = 4'd1;")
DL("    localparam ST_MRC_S1  = 4'd2;")
DL("    localparam ST_MRC_S2  = 4'd3;")
DL("    localparam ST_MRC_S3  = 4'd4;")
DL("    localparam ST_MRC_S4  = 4'd5;")
DL("    localparam ST_MRC_S5  = 4'd6;")
DL("    localparam ST_DIST_S1 = 4'd7;")
DL("    localparam ST_DIST_S2 = 4'd8;")
DL("    localparam ST_DIST_S3 = 4'd9;")
DL("    localparam ST_UPDATE  = 4'd10;")
DL("    localparam ST_NEXT    = 4'd11;")
DL("    localparam ST_DONE    = 4'd12;")
DL()
DL("    localparam NRM_MAX_ERRORS = 3;")
DL()
DL("    reg [3:0] state;")
DL("    reg [6:0] trip_idx;")
DL()
DL("    // =========================================================================")
DL("    // 2. Lookup Tables for 84 Triplets")
DL("    // =========================================================================")
DL("    reg [6:0] lut_mi [0:83];")
DL("    reg [6:0] lut_mj [0:83];")
DL("    reg [6:0] lut_mk [0:83];")
DL("    reg [6:0] lut_inv_ij  [0:83];")
DL("    reg [6:0] lut_inv_ijk [0:83];")
DL("    reg [3:0] lut_idx_i [0:83];")
DL("    reg [3:0] lut_idx_j [0:83];")
DL("    reg [3:0] lut_idx_k [0:83];")
DL()
DL("    initial begin")
for idx, (i, j, k) in enumerate(triplets):
    inv_ij, inv_ijk, mi, mj, mk = get_mrc_constants(i, j, k)
    DL(f"        lut_mi[{idx:2d}]=7'd{mi}; lut_mj[{idx:2d}]=7'd{mj}; lut_mk[{idx:2d}]=7'd{mk};")
    DL(f"        lut_inv_ij[{idx:2d}]=7'd{inv_ij}; lut_inv_ijk[{idx:2d}]=7'd{inv_ijk};")
    DL(f"        lut_idx_i[{idx:2d}]=4'd{i}; lut_idx_j[{idx:2d}]=4'd{j}; lut_idx_k[{idx:2d}]=4'd{k};")
DL("    end")
DL()
DL("    // =========================================================================")
DL("    // 3. Received Residues Register Bank")
DL("    // =========================================================================")
DL("    reg [6:0] recv_r [0:8];")
DL()
DL("    // =========================================================================")
DL("    // 4. MRC Computation Registers")
DL("    // =========================================================================")
DL("    reg [6:0] mrc_ri, mrc_rj, mrc_rk;")
DL("    // v1.1 TIMING FIX: add max_fanout=8 to mrc_mi/mj/mk to reduce net delay.")
DL("    // Root cause: mrc_mi_reg had fanout=68, causing Net Delay=8.984ns (WNS=-0.107ns).")
DL("    // With max_fanout=8, Vivado replicates the register (~9 copies), reducing")
DL("    // per-copy fanout to ~8 and net delay to ~3-4ns. Expected WNS > +5ns.")
DL("    (* max_fanout = 8 *) reg [6:0] mrc_mi;")
DL("    (* max_fanout = 8 *) reg [6:0] mrc_mj;")
DL("    (* max_fanout = 8 *) reg [6:0] mrc_mk;")
DL("    reg [6:0] mrc_inv_ij, mrc_inv_ijk;")
DL("    reg [3:0] mrc_idx_j, mrc_idx_k;")
DL("    reg [6:0] mrc_a1;")
DL("    reg [7:0] mrc_diff2;")
DL("    reg [7:0] mrc_diff3;")
DL("    // v1.4 TIMING FIX: add pipeline register for a2mi_prod to break long path.")
DL("    // timing22: mrc_a2_reg[2] fanout=80, Net Delay=9.26ns (WNS=-0.614ns).")
DL("    // max_fanout alone insufficient. Add ST_MRC_S3b state to register a2mi_prod.")
DL("    (* max_fanout = 4 *) reg [6:0] mrc_a2;")
DL("    reg [13:0] mrc_a2mi_prod;  // Registered intermediate: a2 * mi (pipeline break)")
DL("    reg [7:0]  mrc_a3raw;")
DL("    reg [6:0] mrc_a3;")
DL("    reg [17:0] mrc_x;")
DL()
DL("    // =========================================================================")
DL("    // 5. Distance Computation Registers")
DL("    // =========================================================================")
DL("    reg [6:0] cand_r [0:8];")
DL("    reg [3:0] cur_dist;")
DL()
DL("    // =========================================================================")
DL("    // 6. MLD Accumulator")
DL("    // =========================================================================")
DL("    reg [3:0]  min_dist;")
DL("    reg [15:0] best_x;")
DL()
DL("    // =========================================================================")
DL("    // 7. Case-Based Constant Modulo Functions (Timing Fix)")
DL("    // =========================================================================")
DL("    // C-RRNS moduli: {64,63,65,67,71,73,79,83,89}")
DL("    function automatic [6:0] mod_by_idx_7bit(input [13:0] val, input [3:0] idx);")
DL("        case (idx)")
DL("            4'd0: mod_by_idx_7bit = val % 7'd64;")
DL("            4'd1: mod_by_idx_7bit = val % 7'd63;")
DL("            4'd2: mod_by_idx_7bit = val % 7'd65;")
DL("            4'd3: mod_by_idx_7bit = val % 7'd67;")
DL("            4'd4: mod_by_idx_7bit = val % 7'd71;")
DL("            4'd5: mod_by_idx_7bit = val % 7'd73;")
DL("            4'd6: mod_by_idx_7bit = val % 7'd79;")
DL("            4'd7: mod_by_idx_7bit = val % 7'd83;")
DL("            4'd8: mod_by_idx_7bit = val % 7'd89;")
DL("            default: mod_by_idx_7bit = 7'd0;")
DL("        endcase")
DL("    endfunction")
DL()
DL("    // =========================================================================")
DL("    // 8. Combinational MRC Intermediate Signals")
DL("    // =========================================================================")
DL("    wire [13:0] s2_prod  = mrc_diff2 * mrc_inv_ij;")
DL("    wire [6:0]  s2_a2    = mod_by_idx_7bit(s2_prod, mrc_idx_j);")
DL()
DL("    wire [13:0] s3_a2mi_prod = mrc_a2 * mrc_mi;")
DL("    wire [6:0]  s3_a2mi_mod  = mod_by_idx_7bit(s3_a2mi_prod, mrc_idx_k);")
DL("    wire [7:0]  s3_a3raw = (mrc_diff3 >= s3_a2mi_mod) ?")
DL("                           (mrc_diff3 - s3_a2mi_mod) :")
DL("                           (mrc_diff3 + mrc_mk - s3_a2mi_mod);")
DL()
DL("    wire [13:0] s4_prod = mrc_a3raw * mrc_inv_ijk;")
DL("    wire [6:0]  s4_a3   = mod_by_idx_7bit(s4_prod, mrc_idx_k);")
DL()
DL("    wire [17:0] s5_x = {11'b0, mrc_a1} + ({11'b0, mrc_a2} * {11'b0, mrc_mi}) +")
DL("                       ({11'b0, mrc_a3} * {11'b0, mrc_mi} * {11'b0, mrc_mj});")
DL()
DL("    // =========================================================================")
DL("    // 9. Combinational Distance Computation")
DL("    // =========================================================================")
DL("    // DIST_S1: cand_r[0..2] = X % {64, 63, 65}")
DL("    wire [6:0] ds1_r0 = mrc_x[15:0] % 7'd64;")
DL("    wire [6:0] ds1_r1 = mrc_x[15:0] % 7'd63;")
DL("    wire [6:0] ds1_r2 = mrc_x[15:0] % 7'd65;")
DL("    // DIST_S2: cand_r[3..5] = X % {67, 71, 73}")
DL("    wire [6:0] ds2_r3 = mrc_x[15:0] % 7'd67;")
DL("    wire [6:0] ds2_r4 = mrc_x[15:0] % 7'd71;")
DL("    wire [6:0] ds2_r5 = mrc_x[15:0] % 7'd73;")
DL("    // DIST_S3: cand_r[6..8] = X % {79, 83, 89}")
DL("    wire [6:0] ds3_r6 = mrc_x[15:0] % 7'd79;")
DL("    wire [6:0] ds3_r7 = mrc_x[15:0] % 7'd83;")
DL("    wire [6:0] ds3_r8 = mrc_x[15:0] % 7'd89;")
DL()
DL("    wire [3:0] dist_comb =")
DL("        ((cand_r[0] != recv_r[0]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[1] != recv_r[1]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[2] != recv_r[2]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[3] != recv_r[3]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[4] != recv_r[4]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[5] != recv_r[5]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[6] != recv_r[6]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[7] != recv_r[7]) ? 4'd1 : 4'd0) +")
DL("        ((cand_r[8] != recv_r[8]) ? 4'd1 : 4'd0);")
DL()
DL("    // =========================================================================")
DL("    // 10. FSM")
DL("    // =========================================================================")
DL("    integer ii;")
DL()
DL("    always @(posedge clk or negedge rst_n) begin")
DL("        if (!rst_n) begin")
DL("            state <= ST_IDLE; trip_idx <= 7'd0;")
DL("            min_dist <= 4'd9; best_x <= 16'd0; cur_dist <= 4'd9;")
DL("            mrc_ri<=7'd0; mrc_rj<=7'd0; mrc_rk<=7'd0;")
DL("            mrc_mi<=7'd1; mrc_mj<=7'd1; mrc_mk<=7'd1;")
DL("            mrc_inv_ij<=7'd1; mrc_inv_ijk<=7'd1;")
DL("            mrc_idx_j<=4'd0; mrc_idx_k<=4'd0;")
DL("            mrc_a1<=7'd0; mrc_diff2<=8'd0; mrc_diff3<=8'd0;")
DL("            mrc_a2<=7'd0; mrc_a3raw<=8'd0; mrc_a3<=7'd0; mrc_x<=18'd0;")
DL("            for (ii=0; ii<9; ii=ii+1) begin recv_r[ii]<=7'd0; cand_r[ii]<=7'd0; end")
DL("            data_out<=16'd0; valid<=1'b0; uncorrectable<=1'b0;")
DL("        end else begin")
DL("            valid <= 1'b0; uncorrectable <= 1'b0;")
DL("            case (state)")
DL("                ST_IDLE: begin")
DL("                    if (start) state <= ST_LOAD;")
DL("                end")
DL("                ST_LOAD: begin")
DL("                    // Unpack received residues from 64-bit bus")
DL("                    recv_r[0] <= {1'b0, residues_in[60:55]};  // mod 64 (6-bit)")
DL("                    recv_r[1] <= {1'b0, residues_in[54:49]};  // mod 63 (6-bit)")
DL("                    recv_r[2] <=        residues_in[48:42];   // mod 65 (7-bit)")
DL("                    recv_r[3] <=        residues_in[41:35];   // mod 67 (7-bit)")
DL("                    recv_r[4] <=        residues_in[34:28];   // mod 71 (7-bit)")
DL("                    recv_r[5] <=        residues_in[27:21];   // mod 73 (7-bit)")
DL("                    recv_r[6] <=        residues_in[20:14];   // mod 79 (7-bit)")
DL("                    recv_r[7] <=        residues_in[13:7];    // mod 83 (7-bit)")
DL("                    recv_r[8] <=        residues_in[6:0];     // mod 89 (7-bit)")
DL("                    trip_idx <= 7'd0; min_dist <= 4'd9; best_x <= 16'd0;")
DL("                    state <= ST_MRC_S1;")
DL("                end")
DL("                ST_MRC_S1: begin")
DL("                    mrc_mi<=lut_mi[trip_idx]; mrc_mj<=lut_mj[trip_idx]; mrc_mk<=lut_mk[trip_idx];")
DL("                    mrc_inv_ij<=lut_inv_ij[trip_idx]; mrc_inv_ijk<=lut_inv_ijk[trip_idx];")
DL("                    mrc_idx_j<=lut_idx_j[trip_idx]; mrc_idx_k<=lut_idx_k[trip_idx];")
DL("                    mrc_ri<=recv_r[lut_idx_i[trip_idx]];")
DL("                    mrc_rj<=recv_r[lut_idx_j[trip_idx]];")
DL("                    mrc_rk<=recv_r[lut_idx_k[trip_idx]];")
DL("                    state <= ST_MRC_S2;")
DL("                end")
DL("                ST_MRC_S2: begin")
DL("                    mrc_a1 <= mrc_ri;")
DL("                    mrc_diff2 <= (mrc_rj>=mrc_ri) ? (mrc_rj-mrc_ri) : (mrc_rj+mrc_mj-mrc_ri);")
DL("                    mrc_diff3 <= (mrc_rk>=mrc_ri) ? (mrc_rk-mrc_ri) : (mrc_rk+mrc_mk-mrc_ri);")
DL("                    state <= ST_MRC_S3;")
DL("                end")
DL("                ST_MRC_S3: begin mrc_a2 <= s2_a2; state <= ST_MRC_S4; end")
DL("                ST_MRC_S4: begin mrc_a3raw <= s3_a3raw; state <= ST_MRC_S5; end")
DL("                ST_MRC_S5: begin mrc_a3 <= s4_a3; state <= ST_DIST_S1; end")
DL("                ST_DIST_S1: begin mrc_x <= s5_x; state <= ST_DIST_S2; end")
DL("                ST_DIST_S2: begin")
DL("                    if (mrc_x <= 18'd65535) begin")
DL("                        cand_r[0]<=ds1_r0; cand_r[1]<=ds1_r1; cand_r[2]<=ds1_r2;")
DL("                    end else begin")
DL("                        cand_r[0]<=7'd127; cand_r[1]<=7'd127; cand_r[2]<=7'd127;")
DL("                    end")
DL("                    state <= ST_DIST_S3;")
DL("                end")
DL("                ST_DIST_S3: begin")
DL("                    if (mrc_x <= 18'd65535) begin")
DL("                        cand_r[3]<=ds2_r3; cand_r[4]<=ds2_r4; cand_r[5]<=ds2_r5;")
DL("                        cand_r[6]<=ds3_r6; cand_r[7]<=ds3_r7; cand_r[8]<=ds3_r8;")
DL("                    end else begin")
DL("                        cand_r[3]<=7'd127; cand_r[4]<=7'd127; cand_r[5]<=7'd127;")
DL("                        cand_r[6]<=7'd127; cand_r[7]<=7'd127; cand_r[8]<=7'd127;")
DL("                    end")
DL("                    state <= ST_UPDATE;")
DL("                end")
DL("                ST_UPDATE: begin")
DL("                    cur_dist <= dist_comb;")
DL("                    if (dist_comb < min_dist) begin")
DL("                        min_dist <= dist_comb; best_x <= mrc_x[15:0];")
DL("                    end")
DL("                    state <= ST_NEXT;")
DL("                end")
DL("                ST_NEXT: begin")
DL("                    if (trip_idx == 7'd83) state <= ST_DONE;")
DL("                    else begin trip_idx <= trip_idx + 1'b1; state <= ST_MRC_S1; end")
DL("                end")
DL("                ST_DONE: begin")
DL("                    valid <= 1'b1;")
DL("                    if (min_dist <= NRM_MAX_ERRORS) begin")
DL("                        data_out <= best_x; uncorrectable <= 1'b0;")
DL("                    end else begin")
DL("                        data_out <= 16'd0; uncorrectable <= 1'b1;")
DL("                    end")
DL("                    state <= ST_IDLE;")
DL("                end")
DL("                default: state <= ST_IDLE;")
DL("            endcase")
DL("        end")
DL("    end")
DL()
DL("endmodule")

# Write decoder (now named decoder_crrns_mld.v)
dec_path = r"d:\FPGAproject\FPGA-RRNS-Project-V2\src\algo_wrapper\decoder_crrns_mld.v"
with open(dec_path, "w", encoding="utf-8") as f:
    f.write("\n".join(dec_lines) + "\n")
print(f"Generated {dec_path} ({len(dec_lines)} lines)")
print("Done!")
