"""
gen_decoder_3nrm_v2.py
Generates decoder_3nrm.v v2.0 - 3NRM-RRNS decoder with FSM-based sequential MRC.

Architecture: Single MRC engine + FSM iterates through all 84 triplets sequentially.
- LUT usage: ~800-1500 LUT (vs ~64,700 LUT for 84-parallel version)
- Latency: ~84 * 5 + overhead = ~430 clock cycles (well within 10,000 watchdog)
- Correctness: identical to parallel version

FSM States:
  IDLE      -> wait for start
  LOAD      -> latch input residues, init loop counter
  MRC_S1    -> compute a1, diff2, diff3
  MRC_S2    -> compute a2 = (diff2 * INV_IJ) % MJ
  MRC_S3    -> compute a3_raw = (diff3 - a2*MI % MK + MK) % MK
  MRC_S4    -> compute a3 = (a3_raw * INV_IJK) % MK
  MRC_S5    -> compute X = a1 + a2*MI + a3*MI*MJ
  DIST_S1   -> compute candidate residues mod all 9 moduli (step 1: mod 64,63,65)
  DIST_S2   -> compute candidate residues (step 2: mod 31,29,23)
  DIST_S3   -> compute candidate residues (step 3: mod 19,17,11) + Hamming distance
  UPDATE    -> update min_dist / best_x if current dist < min_dist
  NEXT      -> increment triplet counter, loop back or go to DONE
  DONE      -> output result for 1 cycle, go to IDLE

Total cycles per triplet: 10 (MRC_S1..S5 + DIST_S1..S3 + UPDATE + NEXT)
Total latency: 1(LOAD) + 84*10 + 1(DONE) = 842 cycles
"""

from math import gcd

def extended_gcd(a, b):
    if a == 0: return b, 0, 1
    g, x, y = extended_gcd(b % a, a)
    return g, y - (b // a) * x, x

def mod_inv(a, m):
    a = a % m
    _, x, _ = extended_gcd(a, m)
    return x % m

MODS = [64, 63, 65, 31, 29, 23, 19, 17, 11]

# Generate all 84 triplets
triplets = [(i,j,k) for i in range(9) for j in range(i+1,9) for k in range(j+1,9)]
assert len(triplets) == 84

# Precompute MRC constants for each triplet
def get_mrc_constants(i, j, k):
    mi, mj, mk = MODS[i], MODS[j], MODS[k]
    inv_ij  = mod_inv(mi, mj)
    inv_ijk = mod_inv((mi * mj) % mk, mk)
    return inv_ij, inv_ijk, mi, mj, mk

# Build lookup tables for all 84 triplets
MI_TABLE   = []
MJ_TABLE   = []
MK_TABLE   = []
INV_IJ_TABLE  = []
INV_IJK_TABLE = []
IDX_I_TABLE = []
IDX_J_TABLE = []
IDX_K_TABLE = []

for (i, j, k) in triplets:
    inv_ij, inv_ijk, mi, mj, mk = get_mrc_constants(i, j, k)
    MI_TABLE.append(mi)
    MJ_TABLE.append(mj)
    MK_TABLE.append(mk)
    INV_IJ_TABLE.append(inv_ij)
    INV_IJK_TABLE.append(inv_ijk)
    IDX_I_TABLE.append(i)
    IDX_J_TABLE.append(j)
    IDX_K_TABLE.append(k)

def format_table(name, values, bits, per_line=8):
    lines = []
    lines.append(f"    // {name} lookup table (84 entries)")
    lines.append(f"    reg [{bits-1}:0] {name} [0:83];")
    lines.append(f"    initial begin")
    for idx, v in enumerate(values):
        lines.append(f"        {name}[{idx:2d}] = {bits}'d{v};")
    lines.append(f"    end")
    return "\n".join(lines)

# Generate Verilog
lines = []
def L(s=""): lines.append(s)

L("// =============================================================================")
L("// File: decoder_3nrm.v")
L("// Description: 3NRM-RRNS Decoder - FSM Sequential MRC Architecture")
L("//              Algorithm: Residue Number System with Moduli Set:")
L("//              Non-redundant: {64, 63, 65}")
L("//              Redundant:     {31, 29, 23, 19, 17, 11}")
L("//              Part of FPGA Multi-Algorithm Fault-Tolerant Test System")
L("// Version: v2.0 (FSM Sequential - Low LUT, ~800-1500 LUT)")
L("//")
L("// ARCHITECTURE: Single MRC engine + FSM iterates through all 84 triplets.")
L("//   - LUT: ~800-1500 (vs ~64,700 for 84-parallel v1.0)")
L("//   - Latency: ~842 clock cycles (well within 10,000-cycle watchdog)")
L("//   - Correctness: identical to parallel version")
L("//")
L("// INPUT BIT LAYOUT (48 bits valid, right-aligned in 64-bit bus):")
L("//   [63:48] = padding (ignored)")
L("//   [47:42] = r0 = received residue mod 64  (6 bits)")
L("//   [41:36] = r1 = received residue mod 63  (6 bits)")
L("//   [35:29] = r2 = received residue mod 65  (7 bits)")
L("//   [28:24] = r3 = received residue mod 31  (5 bits)")
L("//   [23:19] = r4 = received residue mod 29  (5 bits)")
L("//   [18:14] = r5 = received residue mod 23  (5 bits)")
L("//   [13:9]  = r6 = received residue mod 19  (5 bits)")
L("//   [8:4]   = r7 = received residue mod 17  (5 bits)")
L("//   [3:0]   = r8 = received residue mod 11  (4 bits)")
L("//")
L("// FSM STATES (10 cycles per triplet, 84 triplets = 840 + 2 overhead = 842 cycles):")
L("//   IDLE, LOAD, MRC_S1..S5, DIST_S1..S3, UPDATE, NEXT, DONE")
L("// =============================================================================")
L()
L("`timescale 1ns / 1ps")
L()
L("module decoder_3nrm (")
L("    input  wire        clk,")
L("    input  wire        rst_n,")
L("    input  wire        start,")
L("    input  wire [63:0] residues_in,")
L("    output reg  [15:0] data_out,")
L("    output reg         valid,")
L("    output reg         uncorrectable")
L(");")
L()
L("    // =========================================================================")
L("    // 1. FSM State Encoding")
L("    // =========================================================================")
L("    localparam ST_IDLE    = 4'd0;")
L("    localparam ST_LOAD    = 4'd1;")
L("    localparam ST_MRC_S1  = 4'd2;")
L("    localparam ST_MRC_S2  = 4'd3;")
L("    localparam ST_MRC_S3  = 4'd4;")
L("    localparam ST_MRC_S4  = 4'd5;")
L("    localparam ST_MRC_S5  = 4'd6;")
L("    localparam ST_DIST_S1 = 4'd7;")
L("    localparam ST_DIST_S2 = 4'd8;")
L("    localparam ST_DIST_S3 = 4'd9;")
L("    localparam ST_UPDATE  = 4'd10;")
L("    localparam ST_NEXT    = 4'd11;")
L("    localparam ST_DONE    = 4'd12;")
L()
L("    localparam NRM_MAX_ERRORS = 3;")
L()
L("    reg [3:0] state;")
L("    reg [6:0] trip_idx;  // 0..83: current triplet index")
L()
L("    // =========================================================================")
L("    // 2. Lookup Tables for 84 Triplets (synthesized as ROM/LUTRAM)")
L("    // =========================================================================")
L("    // Moduli for each triplet")
L("    reg [6:0] lut_mi [0:83];")
L("    reg [6:0] lut_mj [0:83];")
L("    reg [6:0] lut_mk [0:83];")
L("    // Modular inverses")
L("    reg [6:0] lut_inv_ij  [0:83];  // Inv(mi mod mj, mj)")
L("    reg [6:0] lut_inv_ijk [0:83];  // Inv(mi*mj mod mk, mk)")
L("    // Residue indices")
L("    reg [3:0] lut_idx_i [0:83];")
L("    reg [3:0] lut_idx_j [0:83];")
L("    reg [3:0] lut_idx_k [0:83];")
L()
L("    initial begin")
for idx, (i, j, k) in enumerate(triplets):
    inv_ij, inv_ijk, mi, mj, mk = get_mrc_constants(i, j, k)
    L(f"        lut_mi[{idx:2d}]=7'd{mi}; lut_mj[{idx:2d}]=7'd{mj}; lut_mk[{idx:2d}]=7'd{mk};")
    L(f"        lut_inv_ij[{idx:2d}]=7'd{inv_ij}; lut_inv_ijk[{idx:2d}]=7'd{inv_ijk};")
    L(f"        lut_idx_i[{idx:2d}]=4'd{i}; lut_idx_j[{idx:2d}]=4'd{j}; lut_idx_k[{idx:2d}]=4'd{k};")
L("    end")
L()
L("    // =========================================================================")
L("    // 3. Received Residues Register Bank")
L("    // =========================================================================")
L("    reg [6:0] recv_r [0:8];  // Latched received residues")
L()
L("    // =========================================================================")
L("    // 4. MRC Computation Registers")
L("    // =========================================================================")
L("    reg [6:0] mrc_ri, mrc_rj, mrc_rk;  // Selected residues for current triplet")
L("    reg [6:0] mrc_mi, mrc_mj, mrc_mk;  // Selected moduli")
L("    reg [6:0] mrc_inv_ij, mrc_inv_ijk; // Selected inverses")
L("    reg [6:0] mrc_a1;                  // a1 = ri")
L("    reg [7:0] mrc_diff2;               // (rj - ri + mj) % mj")
L("    reg [7:0] mrc_diff3;               // (rk - ri + mk) % mk")
L("    reg [6:0] mrc_a2;                  // a2 = (diff2 * inv_ij) % mj")
L("    reg [7:0] mrc_a3raw;               // a3_raw = (diff3 - a2*mi%mk + mk) % mk")
L("    reg [6:0] mrc_a3;                  // a3 = (a3_raw * inv_ijk) % mk")
L("    reg [17:0] mrc_x;                  // X = a1 + a2*mi + a3*mi*mj")
L()
L("    // =========================================================================")
L("    // 5. Distance Computation Registers")
L("    // =========================================================================")
L("    reg [6:0] cand_r [0:8];  // Candidate residues for current X")
L("    reg [3:0] cur_dist;      // Hamming distance for current triplet")
L()
L("    // =========================================================================")
L("    // 6. MLD Accumulator")
L("    // =========================================================================")
L("    reg [3:0]  min_dist;   // Minimum distance seen so far")
L("    reg [15:0] best_x;     // Best candidate X")
L()
L("    // =========================================================================")
L("    // 7. Combinational MRC Intermediate Signals")
L("    // =========================================================================")
L("    // MRC_S2: a2 = (diff2 * inv_ij) % mj")
L("    wire [13:0] s2_prod  = mrc_diff2 * mrc_inv_ij;")
L("    wire [6:0]  s2_a2    = s2_prod % mrc_mj;")
L()
L("    // MRC_S3: a3_raw = (diff3 - (a2*mi % mk) + mk) % mk")
L("    wire [13:0] s3_a2mi_prod = mrc_a2 * mrc_mi;")
L("    wire [6:0]  s3_a2mi_mod  = s3_a2mi_prod % mrc_mk;")
L("    wire [7:0]  s3_a3raw = (mrc_diff3 >= s3_a2mi_mod) ?")
L("                           (mrc_diff3 - s3_a2mi_mod) :")
L("                           (mrc_diff3 + mrc_mk - s3_a2mi_mod);")
L()
L("    // MRC_S4: a3 = (a3_raw * inv_ijk) % mk")
L("    wire [13:0] s4_prod = mrc_a3raw * mrc_inv_ijk;")
L("    wire [6:0]  s4_a3   = s4_prod % mrc_mk;")
L()
L("    // MRC_S5: X = a1 + a2*mi + a3*mi*mj")
L("    wire [17:0] s5_x = {11'b0, mrc_a1} + ({11'b0, mrc_a2} * {11'b0, mrc_mi}) +")
L("                       ({11'b0, mrc_a3} * {11'b0, mrc_mi} * {11'b0, mrc_mj});")
L()
L("    // =========================================================================")
L("    // 8. Combinational Distance Computation")
L("    // =========================================================================")
L("    // DIST_S1: compute cand_r[0..2] = X % {64, 63, 65}")
L("    wire [6:0] ds1_r0 = mrc_x[15:0] % 7'd64;")
L("    wire [6:0] ds1_r1 = mrc_x[15:0] % 7'd63;")
L("    wire [6:0] ds1_r2 = mrc_x[15:0] % 7'd65;")
L()
L("    // DIST_S2: compute cand_r[3..5] = X % {31, 29, 23}")
L("    wire [6:0] ds2_r3 = mrc_x[15:0] % 7'd31;")
L("    wire [6:0] ds2_r4 = mrc_x[15:0] % 7'd29;")
L("    wire [6:0] ds2_r5 = mrc_x[15:0] % 7'd23;")
L()
L("    // DIST_S3: compute cand_r[6..8] = X % {19, 17, 11} + Hamming distance")
L("    wire [6:0] ds3_r6 = mrc_x[15:0] % 7'd19;")
L("    wire [6:0] ds3_r7 = mrc_x[15:0] % 7'd17;")
L("    wire [6:0] ds3_r8 = mrc_x[15:0] % 7'd11;")
L()
L("    // Hamming distance: count mismatches between cand_r[0..8] and recv_r[0..8]")
L("    // Computed after DIST_S3 latches cand_r[6..8]")
L("    wire [3:0] dist_comb =")
L("        ((cand_r[0] != recv_r[0]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[1] != recv_r[1]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[2] != recv_r[2]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[3] != recv_r[3]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[4] != recv_r[4]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[5] != recv_r[5]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[6] != recv_r[6]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[7] != recv_r[7]) ? 4'd1 : 4'd0) +")
L("        ((cand_r[8] != recv_r[8]) ? 4'd1 : 4'd0);")
L()
L("    // =========================================================================")
L("    // 9. FSM")
L("    // =========================================================================")
L("    integer ii;")
L()
L("    always @(posedge clk or negedge rst_n) begin")
L("        if (!rst_n) begin")
L("            state         <= ST_IDLE;")
L("            trip_idx      <= 7'd0;")
L("            min_dist      <= 4'd9;")
L("            best_x        <= 16'd0;")
L("            cur_dist      <= 4'd9;")
L("            mrc_ri        <= 7'd0;")
L("            mrc_rj        <= 7'd0;")
L("            mrc_rk        <= 7'd0;")
L("            mrc_mi        <= 7'd1;")
L("            mrc_mj        <= 7'd1;")
L("            mrc_mk        <= 7'd1;")
L("            mrc_inv_ij    <= 7'd1;")
L("            mrc_inv_ijk   <= 7'd1;")
L("            mrc_a1        <= 7'd0;")
L("            mrc_diff2     <= 8'd0;")
L("            mrc_diff3     <= 8'd0;")
L("            mrc_a2        <= 7'd0;")
L("            mrc_a3raw     <= 8'd0;")
L("            mrc_a3        <= 7'd0;")
L("            mrc_x         <= 18'd0;")
L("            for (ii=0; ii<9; ii=ii+1) begin")
L("                recv_r[ii] <= 7'd0;")
L("                cand_r[ii] <= 7'd0;")
L("            end")
L("            data_out      <= 16'd0;")
L("            valid         <= 1'b0;")
L("            uncorrectable <= 1'b0;")
L("        end else begin")
L("            valid         <= 1'b0;")
L("            uncorrectable <= 1'b0;")
L()
L("            case (state)")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_IDLE: begin")
L("                    if (start) begin")
L("                        state <= ST_LOAD;")
L("                    end")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_LOAD: begin")
L("                    // Latch received residues from input bus")
L("                    recv_r[0] <= {1'b0, residues_in[47:42]};  // mod 64")
L("                    recv_r[1] <= {1'b0, residues_in[41:36]};  // mod 63")
L("                    recv_r[2] <=        residues_in[35:29];   // mod 65")
L("                    recv_r[3] <= {2'b0, residues_in[28:24]};  // mod 31")
L("                    recv_r[4] <= {2'b0, residues_in[23:19]};  // mod 29")
L("                    recv_r[5] <= {2'b0, residues_in[18:14]};  // mod 23")
L("                    recv_r[6] <= {2'b0, residues_in[13:9]};   // mod 19")
L("                    recv_r[7] <= {2'b0, residues_in[8:4]};    // mod 17")
L("                    recv_r[8] <= {3'b0, residues_in[3:0]};    // mod 11")
L("                    // Initialize MLD accumulators")
L("                    trip_idx  <= 7'd0;")
L("                    min_dist  <= 4'd9;")
L("                    best_x    <= 16'd0;")
L("                    state     <= ST_MRC_S1;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_MRC_S1: begin")
L("                    // Load triplet parameters from LUT")
L("                    // Compute a1, diff2, diff3")
L("                    mrc_mi      <= lut_mi[trip_idx];")
L("                    mrc_mj      <= lut_mj[trip_idx];")
L("                    mrc_mk      <= lut_mk[trip_idx];")
L("                    mrc_inv_ij  <= lut_inv_ij[trip_idx];")
L("                    mrc_inv_ijk <= lut_inv_ijk[trip_idx];")
L("                    mrc_ri      <= recv_r[lut_idx_i[trip_idx]];")
L("                    mrc_rj      <= recv_r[lut_idx_j[trip_idx]];")
L("                    mrc_rk      <= recv_r[lut_idx_k[trip_idx]];")
L("                    // a1 = ri (will be latched next cycle from mrc_ri)")
L("                    state <= ST_MRC_S2;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_MRC_S2: begin")
L("                    // Latch a1, diff2, diff3 (computed from registered mrc_ri/rj/rk)")
L("                    mrc_a1    <= mrc_ri;")
L("                    mrc_diff2 <= (mrc_rj >= mrc_ri) ? (mrc_rj - mrc_ri) :")
L("                                 (mrc_rj + mrc_mj - mrc_ri);")
L("                    mrc_diff3 <= (mrc_rk >= mrc_ri) ? (mrc_rk - mrc_ri) :")
L("                                 (mrc_rk + mrc_mk - mrc_ri);")
L("                    // a2 combinational: s2_a2 = (diff2 * inv_ij) % mj")
L("                    // But diff2 not yet registered, so compute a2 next cycle")
L("                    state <= ST_MRC_S3;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_MRC_S3: begin")
L("                    // Latch a2 (computed from registered mrc_diff2, mrc_inv_ij, mrc_mj)")
L("                    mrc_a2    <= s2_a2;")
L("                    // a3_raw combinational: s3_a3raw (from mrc_diff3, mrc_a2, mrc_mi, mrc_mk)")
L("                    // But a2 not yet registered, so compute a3_raw next cycle")
L("                    state <= ST_MRC_S4;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_MRC_S4: begin")
L("                    // Latch a3_raw (computed from registered mrc_a2, mrc_diff3, mrc_mi, mrc_mk)")
L("                    mrc_a3raw <= s3_a3raw;")
L("                    // a3 combinational: s4_a3 (from mrc_a3raw, mrc_inv_ijk, mrc_mk)")
L("                    // But a3raw not yet registered, so compute a3 next cycle")
L("                    state <= ST_MRC_S5;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_MRC_S5: begin")
L("                    // Latch a3 (computed from registered mrc_a3raw, mrc_inv_ijk, mrc_mk)")
L("                    mrc_a3 <= s4_a3;")
L("                    // X combinational: s5_x (from mrc_a1, mrc_a2, mrc_a3, mrc_mi, mrc_mj)")
L("                    // But a3 not yet registered, so compute X next cycle")
L("                    state <= ST_DIST_S1;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_DIST_S1: begin")
L("                    // Latch X (computed from registered mrc_a1/a2/a3/mi/mj)")
L("                    mrc_x <= s5_x;")
L("                    // Compute cand_r[0..2] = X % {64, 63, 65}")
L("                    // But X not yet registered, so compute next cycle")
L("                    state <= ST_DIST_S2;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_DIST_S2: begin")
L("                    // Latch cand_r[0..2] (from registered mrc_x)")
L("                    // Check if X is in valid range [0, 65535]")
L("                    if (mrc_x <= 18'd65535) begin")
L("                        cand_r[0] <= ds1_r0;")
L("                        cand_r[1] <= ds1_r1;")
L("                        cand_r[2] <= ds1_r2;")
L("                    end else begin")
L("                        // Out of range: set cand_r to impossible values")
L("                        // so distance will be 9 (max), won't be selected")
L("                        cand_r[0] <= 7'd127;")
L("                        cand_r[1] <= 7'd127;")
L("                        cand_r[2] <= 7'd127;")
L("                    end")
L("                    // Compute cand_r[3..5] = X % {31, 29, 23}")
L("                    state <= ST_DIST_S3;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_DIST_S3: begin")
L("                    // Latch cand_r[3..5] (from registered mrc_x)")
L("                    if (mrc_x <= 18'd65535) begin")
L("                        cand_r[3] <= ds2_r3;")
L("                        cand_r[4] <= ds2_r4;")
L("                        cand_r[5] <= ds2_r5;")
L("                        // Latch cand_r[6..8] (from registered mrc_x)")
L("                        cand_r[6] <= ds3_r6;")
L("                        cand_r[7] <= ds3_r7;")
L("                        cand_r[8] <= ds3_r8;")
L("                    end else begin")
L("                        cand_r[3] <= 7'd127;")
L("                        cand_r[4] <= 7'd127;")
L("                        cand_r[5] <= 7'd127;")
L("                        cand_r[6] <= 7'd127;")
L("                        cand_r[7] <= 7'd127;")
L("                        cand_r[8] <= 7'd127;")
L("                    end")
L("                    state <= ST_UPDATE;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_UPDATE: begin")
L("                    // Compute Hamming distance (from registered cand_r[0..8])")
L("                    cur_dist <= dist_comb;")
L("                    // Update min_dist / best_x if current dist < min_dist")
L("                    if (dist_comb < min_dist) begin")
L("                        min_dist <= dist_comb;")
L("                        best_x   <= mrc_x[15:0];")
L("                    end")
L("                    state <= ST_NEXT;")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_NEXT: begin")
L("                    if (trip_idx == 7'd83) begin")
L("                        state <= ST_DONE;")
L("                    end else begin")
L("                        trip_idx <= trip_idx + 1'b1;")
L("                        state    <= ST_MRC_S1;")
L("                    end")
L("                end")
L()
L("                // ─────────────────────────────────────────────────────────")
L("                ST_DONE: begin")
L("                    valid <= 1'b1;")
L("                    if (min_dist <= NRM_MAX_ERRORS) begin")
L("                        data_out      <= best_x;")
L("                        uncorrectable <= 1'b0;")
L("                    end else begin")
L("                        data_out      <= 16'd0;")
L("                        uncorrectable <= 1'b1;")
L("                    end")
L("                    state <= ST_IDLE;")
L("                end")
L()
L("                default: state <= ST_IDLE;")
L("            endcase")
L("        end")
L("    end")
L()
L("endmodule")

# Write to file
output_path = r"d:\FPGAproject\FPGA-RRNS-Project-V2\src\algo_wrapper\decoder_3nrm.v"
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {output_path}")
print(f"Total lines: {len(lines)}")
print(f"Triplets: {len(triplets)}")
print(f"Estimated latency: 1(LOAD) + 84*10(MRC+DIST+UPDATE+NEXT) + 1(DONE) = 842 cycles")
print(f"Estimated LUT: ~800-1500 (FSM + single MRC engine + LUT tables)")
