// =============================================================================
// File: rom_threshold_ctrl.v
// Description: BER Threshold ROM Controller
//              Part of FPGA Multi-Algorithm Fault-Tolerant Test System
//              Implements Design Doc Section 2.3.2.4 (ROM Threshold Lookup)
// Version: v1.0
//
// ─────────────────────────────────────────────────────────────────────────────
// DESIGN OVERVIEW (Section 2.3.2.4):
//   This module provides the LFSR comparison threshold for each BER test point.
//   The threshold table is pre-computed by gen_rom.py and stored in Block RAM.
//   The Main Scan FSM queries this module at the start of each BER point to
//   obtain the 32-bit threshold integer used for error injection probability.
//
// ADDRESS MAPPING (Must match gen_rom.py exactly):
//   Python formula:
//     addr = (algo_id * BER_POINTS * NUM_BURST_STEPS) + (ber_idx * NUM_BURST_STEPS) + (burst_len - 1)
//          = (algo_id * 91 * 15) + (ber_idx * 15) + (burst_len - 1)
//          = (algo_id * 1365)    + (ber_idx * 15)  + (burst_len - 1)
//
//   This is a LINEAR PACKED structure — NOT bit-concatenation.
//   Verilog must implement this arithmetic to match the Python script.
//
//   Address range: 0 ~ 5459 (4 * 91 * 15 = 5460 valid entries)
//   Physical ROM depth: 2^13 = 8192 (covers 5460, unused entries = 0)
//
// TIMING (Request-Valid Handshake):
//   Cycle N:   req=1, address inputs stable
//   Cycle N+1: valid=1, threshold_val contains the looked-up value
//   This single-cycle latency matches BRAM read characteristics at 100MHz.
//
// SAFETY GUARD:
//   If ber_idx >= 91 or burst_len == 0, threshold_val is forced to 0.
//   This prevents accidental injection from out-of-range inputs.
// =============================================================================

`include "rom_threshold_ctrl.vh"

module rom_threshold_ctrl (
    // -------------------------------------------------------------------------
    // Global Clock & Reset
    // -------------------------------------------------------------------------
    input  wire        clk,
    input  wire        rst_n,

    // -------------------------------------------------------------------------
    // Request-Valid Handshake
    // -------------------------------------------------------------------------
    input  wire        req,
    // req=1: Address inputs are valid, perform ROM lookup.
    // Result appears on threshold_val one clock cycle later (valid=1).

    // -------------------------------------------------------------------------
    // Address Inputs (From Main Scan FSM)
    // -------------------------------------------------------------------------
    input  wire [`THRESH_ALGO_BITS-1:0]  algo_id,
    // Algorithm selector: 0=2NRM, 1=3NRM, 2=C-RRNS, 3=RS
    // Selects the correct 1365-entry ROM partition

    input  wire [`THRESH_BER_BITS-1:0]   ber_idx,
    // BER point index: 0~90 (maps to BER 1%~10% in steps of 0.1%)
    // Values >= 91 are treated as invalid (threshold forced to 0)

    input  wire [`THRESH_LEN_BITS-1:0]   burst_len,
    // Burst length L: 1~15. Value 0 is invalid (threshold forced to 0).
    // Address uses (burst_len - 1), mapping L=1->0, L=15->14.

    // -------------------------------------------------------------------------
    // Output
    // -------------------------------------------------------------------------
    output reg  [`THRESH_ROM_DATA_WIDTH-1:0] threshold_val,
    // 32-bit LFSR comparison threshold.
    // Valid one clock cycle after req=1.
    // Usage: if (lfsr_out < threshold_val) → trigger error injection

    output reg         valid
    // Asserted HIGH for one clock cycle when threshold_val is valid.
    // Deasserted when req=0 or after the valid cycle.
);

    // =========================================================================
    // ROM Declaration and Initialization (Section 2.3.2.4)
    // =========================================================================
    // Physical depth: 2^13 = 8192 entries (covers logical depth of 5460).
    // Unused entries (5460~8191) are initialized to 0 by $readmemh.
    // Synthesis attribute forces Vivado to infer Block RAM (not registers).

    (* ram_style = "block" *)
    reg [`THRESH_ROM_DATA_WIDTH-1:0] thresh_rom [0:(1 << `THRESH_ROM_ADDR_WIDTH)-1];

    // Load threshold data from COE file generated by gen_rom.py.
    // File contains 5460 valid 32-bit hex entries (remaining filled with 0).
    initial begin
        $readmemh(`THRESH_ROM_COE_FILE, thresh_rom);
    end

    // =========================================================================
    // Address Calculation (Linear Packed — Must Match gen_rom.py)
    // =========================================================================
    // Python: addr = (algo_id * 1365) + (ber_idx * 15) + (burst_len - 1)
    //
    // Verilog implementation uses arithmetic (not bit-concatenation) because
    // BER_POINTS=91 and BURST_STEPS=15 are not powers of 2.
    //
    // Intermediate widths:
    //   algo_id * 1365: max = 3 * 1365 = 4095 → needs 12 bits
    //   ber_idx * 15:   max = 90 * 15  = 1350 → needs 11 bits
    //   burst_len - 1:  max = 14       → needs 4 bits
    //   Total max addr: 4095 + 1350 + 14 = 5459 → needs 13 bits ✓

    // Constants matching gen_rom.py
    localparam ALGO_STRIDE = `THRESH_BER_POINTS * `THRESH_LEN_STEPS; // 91 * 15 = 1365
    localparam BER_STRIDE  = `THRESH_LEN_STEPS;                       // 15

    // Combinational address computation
    wire [`THRESH_ROM_ADDR_WIDTH-1:0] rom_addr_comb;
    wire addr_valid; // Asserted when all inputs are within legal range

    // Input validity check (Safety Guard):
    //   ber_idx must be 0~90 (< 91)
    //   burst_len must be 1~15 (non-zero)
    // FIX R1: Replaced `THRESH_LEN_BITS'b0 with explicit 4'd0 for clarity.
    //   `THRESH_LEN_BITS is a numeric constant (4), not a type, so using it
    //   as a bit-width prefix is syntactically valid but semantically confusing.
    //   4'd0 is unambiguous: a 4-bit zero, matching burst_len's port width.
    assign addr_valid = (ber_idx < `THRESH_BER_POINTS) && (burst_len != 4'd0);

    // Linear address calculation matching gen_rom.py formula:
    //   addr = (algo_id * 1365) + (ber_idx * 15) + (burst_len - 1)
    assign rom_addr_comb = addr_valid ?
        (({11'b0, algo_id} * ALGO_STRIDE) +
         ({6'b0, ber_idx}  * BER_STRIDE)  +
         ({9'b0, burst_len} - 13'd1))
        : 13'd0;

    // =========================================================================
    // Registered Output Stage (Request-Valid Handshake, 1-cycle latency)
    // =========================================================================
    // Timing:
    //   Cycle N:   req=1, rom_addr_comb is stable
    //   Cycle N+1: valid=1, threshold_val = thresh_rom[rom_addr_comb]
    //
    // This matches the natural BRAM read latency (1 clock cycle) and ensures
    // timing closure at 100MHz without combinational path violations.

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            // -----------------------------------------------------------------
            // Asynchronous Reset: Clear outputs
            // -----------------------------------------------------------------
            threshold_val <= `THRESH_ROM_DATA_WIDTH'h0;
            valid         <= 1'b0;

        end else begin

            if (req && addr_valid) begin
                // -------------------------------------------------------------
                // Valid Request: Perform ROM lookup
                //   Read threshold from ROM at the computed linear address.
                //   Output will be valid on the next clock cycle.
                // -------------------------------------------------------------
                threshold_val <= thresh_rom[rom_addr_comb];
                valid         <= 1'b1;

            end else if (req && !addr_valid) begin
                // -------------------------------------------------------------
                // Invalid Request (Safety Guard):
                //   ber_idx >= 91 or burst_len == 0 → force threshold to 0.
                //   This prevents accidental error injection from illegal inputs.
                //   valid is still asserted so the FSM doesn't stall.
                // -------------------------------------------------------------
                threshold_val <= `THRESH_ROM_DATA_WIDTH'h0;
                valid         <= 1'b1;

            end else begin
                // -------------------------------------------------------------
                // No Request: Deassert valid, hold threshold_val
                // -------------------------------------------------------------
                valid <= 1'b0;
                // threshold_val holds its previous value (don't care when valid=0)
            end

        end
    end

endmodule
